## Array

In [1]:
#3dimensional array is made up of bunch of 2d array.
# 3d array is basically cube(3 sides)

#### Creating an array:
1.  Assign it to a variable.
2.  Define the type of elements that it will store
3.  Define its size (the maximum numbers of elements)(not reqd now as dynamic array!)

In [3]:
# In python,we need to import array module to create an array
from array import *

In [4]:
# arrayName = array(typecode,[Initializers])
#typecode is data type of array's.
# array takes only one datatype unlike lists.

In [5]:
from array import *
arr1 = array('i',[1,2,3,4,5,6])  #'i' for integer

In [6]:
arr1

array('i', [1, 2, 3, 4, 5, 6])

In [11]:
arr2 = array('d',[1.3,1.5,1.6])  #'d' for decimal

In [12]:
arr2

array('d', [1.3, 1.5, 1.6])

In [13]:
arr1 = array('i',[1,2,3,4,5,6])
arr2 = array('d',[1.3,1.5,1.6])
print(arr1)
print(arr2)

array('i', [1, 2, 3, 4, 5, 6])
array('d', [1.3, 1.5, 1.6])


In [14]:
#insertion  (arry shifts element,does not delete it like lists)
arr1.insert(6,7)  #.insert(index,value)
print(arr1)

array('i', [1, 2, 3, 4, 5, 6, 7])


In [15]:
arr1.insert(0,0)
print(arr1)

array('i', [0, 1, 2, 3, 4, 5, 6, 7])


In [16]:
arr1.insert(2,9)
print(arr1)

array('i', [0, 1, 9, 2, 3, 4, 5, 6, 7])


In [18]:
#array traversal using simple loop
arr1 = array('i',[1,2,3,4,5,6])
def traverseArray(array):
    for i in array:
        print(i)
traverseArray(arr1)

1
2
3
4
5
6


In [21]:
# Access array element using indexing
arr1 = array('i',[1,2,3,4,5,6])
def accessElement(array,index):
    if index >= len(array):
        print('There is not any element in this index!')
    else:
        print(array[index])
accessElement(arr1,1)

2


In [23]:
accessElement(arr1,5)

6


In [22]:
accessElement(arr1,6)

There is not any element in this index!


In [24]:
# searching an element inside an array(finding index from value)
arr1 = array('i',[1,2,3,4,5,6])

def searchInArray(array,value):
    for i in array:
        if i == value:
            return arr1.index(value)
    return 'The element does not exist in this array!'

In [25]:
print(searchInArray(arr1,3))

2


In [26]:
print(searchInArray(arr1,6))

5


In [27]:
print(searchInArray(arr1,7))

The element does not exist in this array!


In [28]:
# element deletion
arr1 = array('i',[1,2,3,4,5,6])

arr1.remove(1)  # .remove(value)
print(arr1)

array('i', [2, 3, 4, 5, 6])


In [30]:
arr1 = array('i',[1,2,3,4,5,6])
arr1.remove(4)
print(arr1)

array('i', [1, 2, 3, 5, 6])


In [54]:
# Operations on array

from array import *
#1.create an array and traverse
my_array = array('i',[1,2,3,4,5])
#traverse
for i in my_array:
    print(i)
    
#2.Access individual elements through indexes
print('Step 2')
print(my_array[0])
print(my_array[3])
#3. Append any value to the array using append() method

print('Step 3')
my_array.append(6) #.append(value) adds at last location.
print(my_array)

#4. Insert value in an array using insert() method
print('Step 4')
my_array.insert(3,11) #.index(index,value)
print(my_array)

#5. Extend python array using extend() method
print('Step 5')
my_array1 = array('i',[10,11,12])
my_array.extend(my_array1)
print(my_array)

#6. Add items from list into array using fromlist() method
print('Step 6')
tempList = [20,21,22]
my_array.fromlist(tempList)
print(my_array)

#7. Remove any array element using remove() method
print('Step 7')
my_array.remove(11)  #.remove(value) (first occurence)
print(my_array)

#8. Remove last array element using pop() method
print('Step 8')
my_array.pop()
print(my_array)

#9. Fetch any  element through its index using index() method
print('Step 9')
print(my_array.index(21))  #.index(value)

#10. Reverse a python array  using reverse() method
print('Step 10')
my_array.reverse()
print(my_array)

#11. Get array buffer information through buffer_info() method
print('Step 11')
print(my_array.buffer_info())

#12. Check for number of occurences of an element using count() mehtod
print('Step 12')
my_array.append(11)
print(my_array.count(11))

#13. Convert array to string using tostring() method
#print('Step 13')
# tostring & fromstring method has been removed

#14.Convert array to a python list with same elements using tolist() method
print('Step 14')
print(my_array.tolist())

#15. Append a string to char array using fromstring() method
#print('Step 15')
# fromstring() removed from python.

#16. Slice Elements from an array
print('Step 16')
print(my_array[1:4])
print(my_array[:])

1
2
3
4
5
Step 2
1
4
Step 3
array('i', [1, 2, 3, 4, 5, 6])
Step 4
array('i', [1, 2, 3, 11, 4, 5, 6])
Step 5
array('i', [1, 2, 3, 11, 4, 5, 6, 10, 11, 12])
Step 6
array('i', [1, 2, 3, 11, 4, 5, 6, 10, 11, 12, 20, 21, 22])
Step 7
array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22])
Step 8
array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21])
Step 9
10
Step 10
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1])
Step 11
(2436574909936, 11)
Step 12
2
Step 14
[21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11]
Step 16
array('i', [20, 12, 11])
array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 11])


In [ ]:
# Multidimensional arry

In [ ]:
# 2d array
# Day 1 - 11, 15, 10, 6
# Day 2 - 10, 14, 11, 5
# Day 3 - 12, 17, 12, 8
# Day 4 - 15, 18, 14, 9

In [55]:
# numpy module is best for multidimensional array
import numpy as np
#2d array using numpy
twoDArray = np.array([[11, 15, 10, 6],[10, 14, 11, 5],[12, 17, 12, 8],[15, 18, 14, 9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [69]:
#insertion in 2d array
#np.insert(arr,object,value,axis)
newTwoDArray = np.insert(twoDArray,1,[1,2,3,4],axis= 0) 
print(newTwoDArray)

[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [67]:
newTwoDArray = np.append(twoDArray,[[1,2,3,4]],axis = 0) 
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


In [70]:
#accessing element in 2d array
twoDArray = np.array([[11, 15, 10, 6],[10, 14, 11, 5],[12, 17, 12, 8],[15, 18, 14, 9]])
print(twoDArray)

def accessElements(array,rowIndex,colIndex):
    #when you put [0],it vl give No. of columns.
    if rowIndex >= len(array) or colIndex >= len(array[0]): #like here
        print('Incorrect index')
    else:
        print(array[rowIndex][colIndex])

accessElements(twoDArray,1,2)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11


In [71]:
accessElements(twoDArray,2,3)

8


In [73]:
# traversel - 2d array
twoDArray = np.array([[11, 15, 10, 6],[10, 14, 11, 5],[12, 17, 12, 8],[15, 18, 14, 9]])
print(twoDArray)

def traverseTDArray(array):
    for i in range(len(array)): #for rows
        #if you do len(array[0]),it vl give len of columns
        for j in range(len(array[0])):
            print(array[i][j])
traverseTDArray(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [76]:
#Searching for an element in 2d array (using linear search)
twoDArray = np.array([[11, 15, 10, 6],[10, 14, 11, 5],[12, 17, 12, 8],[15, 18, 14, 9]])
print(twoDArray)

def searchTDArray(array,value):
    #using linear search
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located at index '+ str(i) +" "+ str(j)
    return 'The element is not found!'
print(searchTDArray(twoDArray,14))

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
The value is located at index 1 1


In [77]:
print(searchTDArray(twoDArray,55))

The element is not found!


In [86]:
# Deletion - 2d arry using numpy
import numpy as np
twoDArray = np.array([[11, 15, 10, 6],[10, 14, 11, 5],[12, 17, 12, 8],[15, 18, 14, 9]])
print(twoDArray)

newTDArray = np.delete(twoDArray,3,axis=0)  #np.delete(arr,obj,axis)
print()
print(newTDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]]


### When to use/avoid Arrays
### When to use
- To store multiple variables of same data type
- Random access
### When to avoid
- Same data type elements
- Reserve memory

### Summary
- Arrays are extremely powerful data structures 
- Memory is allocated immediately 
- Elements are located in contiguous locations in memory 
- Indices start at 0 
- Inserting elements 
- Removing elements. 
- Finding elements

In [87]:
### Thank you!